### ISSUE TITLE
Wrap lines at 72 chars

### ISSUE THREAD

**Issue by m1foley** [jorisroovers/gitlint#1]
80 chars is the standard for writing code, but Tim Pope's [authoritative guide](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html) recommends wrapping Git commits at 72. The community has largely agreed on this standard; the [Pro Git](https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project) book mentions it too.

**Comment by jorisroovers** [comment]
Yes :-) I personally prefer 80 over 72 and hardcoded it this way in the beginning before gitlint could take config to change the length. I'll change it to 72 now, thanks!

**Comment by jorisroovers** [comment]
Fixed in bca148c1edc59d87a861d39991faa45a8ab2e266
