### ISSUE TITLE
Config Error: No such rule 'contrib-title-conventional-commits'

### ISSUE THREAD

**Issue by CMiksche** [jorisroovers/gitlint#103]
I really want to use the new `contrib-title-conventional-commits` rule to enforce Angular style commit messages. 
However, if i add the rule to my .gitlint file, gitlint shows me the error `Config Error: No such rule 'contrib-title-conventional-commits'`.
I am using gitlint 0.12.0, here is my .gitlint:

```
[contrib-title-conventional-commits]
types = build,ci,docs,feat,fix,perf,refactor,style,test
```

Output of `gitlint --debug`:

```
DEBUG: gitlint.cli Platform: Windows-10-10.0.18362-SP0
DEBUG: gitlint.cli Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
DEBUG: gitlint.cli Git version: git version 2.17.1.windows.2
DEBUG: gitlint.cli Gitlint version: 0.12.0
DEBUG: gitlint.cli GITLINT_USE_SH_LIB: [NOT SET]
Config Error: No such rule 'contrib-title-conventional-commits'
```

After reading #84 - i had assumed, that the new rule should work?!

**Comment by jorisroovers** [comment]
Contrib rules have to be enabled one by one, your snippet only configures the rule, it doesn’t enable it - see below. 

‘’’ini
[general]
contrib=contrib-title-conventional-commits
‘’’

More details: http://jorisroovers.com/gitlint/contrib_rules/

Let me know if this works for you!

Btw, I’ve definitely given thought to removing this extra step, but the benefit is that it allows you to quickly disable/enable the rules without  having to modify the rest of the file. It’s also similar to how ignoring rules work in gitlint and other linters - the rationale was to keep things consistent. Food for thought...

**Comment by CMiksche** [comment]
Thank you for clarification. This works for me.
