### ISSUE TITLE
New Rule: body-match-regex

### ISSUE THREAD

**Issue by strk** [jorisroovers/gitlint#130]
There's a `title-match-regex` rule but no `body-match-regex`, how do I match the whole commit log to make sure a ticket reference exists, no matter if in title or body ?

**Comment by jorisroovers** [comment]
Hi!

That rule indeed doesn't exist. Happy to accept PR for `body-match-regex` and/or `commit-match-regex` :-)

Meanwhile, you should be able to work around this pretty easily using
https://jorisroovers.com/gitlint/user_defined_rules/

**Comment by strk** [comment]
See #131 for `body-match-regex`
