### ISSUE TITLE
Add title-min-length rule

### ISSUE THREAD

**Issue by tjanez** [jorisroovers/gitlint#138]
It would be similar to the `body-min-length` rule and would quickly detect bad commit messages like "Fix", "Bump", ...

**Comment by jorisroovers** [comment]
Makes sense. Any thoughts on what the best default limitation should be?
This can be done purely by (configurable) char count -  e.g. min 5 chars -  or by needing at least 2 words.

I'm inclined to keep it simple to start and going for min 5 chars.

**Comment by tjanez** [comment]
> Any thoughts on what the best default limitation should be?
> This can be done purely by (configurable) char count - e.g. min 5 chars - or by needing at least 2 words.

Hmm... I also though at doing char count first. At least 2 words probably also makes sense since I can't come up with a good one word commit message example :slightly_smiling_face:.

> I'm inclined to keep it simple to start and going for min 5 chars.

Yes, I think this would be a good start.
