### ISSUE TITLE
Add a rule to disallow commit messages starting with "fixup!"

### ISSUE THREAD

**Issue by tjanez** [jorisroovers/gitlint#139]
They are created with the `git commit --fixup=<commit-sha>` command and are supposed to be squashed.

If they are present, they usually indicate that someone forgot to do `git rebase -i` and squash them.

A similar thing could be achieved with the `title-must-not-contain-word` rule, but unfortunately, the currently used regex:
https://github.com/jorisroovers/gitlint/blob/7f7c52fc2ee54ef8d8f1cfa8033b457c1cbac6b2/gitlint/rules.py#L158

prevents using the `fixup!` word since then the regex doesn't match at all:

```
In [11]: re.search(r"\b%s\b" % "fixup", "fixup! Some title")                    
Out[11]: <re.Match object; span=(0, 5), match='fixup'>

In [12]: re.search(r"\b%s\b" % "fixup!", "fixup! Some title")
```

Simply using `fixup` as a forbidden word is an incomplete solution since the term "fixup" is valid in other parts of the title, e.g.: "Add another check to fixup tests"

**Comment by jorisroovers** [comment]
So given that [gitlint actually ignores fixup commits by default](https://jorisroovers.com/gitlint/#merge-fixup-and-squash-commits), I think this is probably a good candidate for a [Contrib Rule](https://jorisroovers.com/gitlint/contrib_rules/) (PRs appreciated!)

Good news is that gitlint already knows whether commits are fixup commits or not, so implementing this as a [User Defined](https://jorisroovers.com/gitlint/user_defined_rules/) or Contrib Rule is easy:

```python
from gitlint.rules import CommitRule, RuleViolation

class DisallowFixup(CommitRule):
    name = "fixup-disallowed"
    # A rule MUST have a *unique* id, we recommend starting with UC (for User-defined Commit-rule) 
    id = "UC1"

    def validate(self, commit):
        if commit.is_fixup_commit:
            return [RuleViolation(self.id, "Don't use fixup! commits (use squash)", line_nr=1)]
```

To invoke:

```bash
gitlint -c general.ignore-fixup-commits=false --extra-path ~/joe/myrules/disallow-fixup.py

# You can also use a .gitlint file instead of commandline flags:
$ cat .gitlint
[general]
ignore-fixup-commits=false
extra-path=~/joe/myrules/disallow-fixup.py
```

Hope this helps!

**Comment by tjanez** [comment]
@jorisroovers, thanks for your helpful reply!

I've decided to implement this as a User Defined Rule first.
For anyone curious, this is how I've done it for the [Oasis Rosetta Gateway](https://github.com/oasisprotocol/oasis-core-rosetta-gateway/commit/c2ce3395f7775410c2f3bf2ffaaa5c518f1e0044) project.

Agreed that this would be a good candidate for a Contrib Rule.
