### ISSUE TITLE
Add footer section in commit message

### ISSUE THREAD

**Issue by innerout** [jorisroovers/gitlint#143]
Hello Joris, I recently started porting the commit template of our project to gitlint, and at the moment, the title and the body are linted by gitlint without any particular problem. At the bottom of our template, we add the issues that possibly are closed by the commit. We call this section the footer, and a newline always separates it by the body.

An example of our template is: 
feat Add feature X

Explain feature X

Closes #number

My question is, Is it possible to extend gitlint to be aware of the footer section or could I manage doing that with the existing features of gitlint?

**Comment by jorisroovers** [comment]
Hi!

Have you looked at gitlint's [user-defined rules](https://jorisroovers.com/gitlint/user_defined_rules/)?

I think something like this should work:

```python
from gitlint.rules import CommitRule, RuleViolation

class FooterRule(object):
""" Common parent class for all Footer rules """

    def validate(self, commit):
        # Extract footer from commit message body
        self.footer = commit.message.body[-2]

# Extend MyCustomRule from both CommitRule (so gitlint will find it) and FooterRule (to implement common footer logic)
class MyCustomRule(CommitRule, FooterRule):
    name = "my-customer-rule"
    id = "UC1"

    def validate(self, commit):
        # call validate method from FooterRule to easily extract footer
        super(MyCustomRule, self).validate(commit)
        # You can obviously do whatever business logic in here to determine the validity of the footer
        message = "Footer contains a problem!"
        return [RuleViolation(self.id, message, content=self.footer, line_nr=len(commit.message.body))]
```

Invoke using:

```python
gitlint -e /tmp/myrules/my_rules.py
```

Hope that helps!

**Comment by innerout** [comment]
I saw user-defined rules, but it did not pass from my mind that I could solve it like that. I will try your suggestion, and I will report back. Thanks!

**Comment by innerout** [comment]
Everything worked perfectly using your suggestion!
