### ISSUE TITLE
Provide Instructions to use gitlint as library

### ISSUE THREAD

**Issue by kuwv** [jorisroovers/gitlint#147]
I'd like to setup CI processes that trigger based on conventional commit messages. Is there a way to use gitlint to interface the last message as a parsed object? And if so, could you provide some instructions please?

Thank you for providing this excellent tool.

**Comment by sigmavirus24** [comment]
It's not described in [usage](https://jorisroovers.com/gitlint/#usage) or anywhere else in the docs there so I'd take that as a strong signal that gitlint isn't intended to be used as a library

**Comment by kuwv** [comment]
Yes, that is very possible. I'd still like to know though for sure though before I attempt to write my own solution.

**Comment by sigmavirus24** [comment]
@kuwv I would suggest moving on as if it doesn't because the maintainer has very little time and will likely tell you no anyway.

**Comment by jorisroovers** [comment]
So, gitlint indeed isn't meant to be consumed as a library to interact with git. There's other tools for that, for example [GitPython](https://github.com/gitpython-developers/GitPython).

Having said that, technically it is possible to [ignore](https://jorisroovers.com/gitlint/configuration/#ignore) all rules except for a single [user-defined](https://jorisroovers.com/gitlint/user_defined_rules/) rule which you can use to do whatever you want (e.g. trigger other CI processes). As the docs explain, that user-defined rule will have the git commit passed to it as a parsed object.

Not sure if that's the best use of gitlint, but I'm not judging :-)

**Comment by kuwv** [comment]
I'm familiar with GitPython and have been using it regularly. I figured as much but wanted to make sure I wasn't missing something. Even with GitPython's features, parsing git messages isn't in it's capability set.

sigmavirus24 jorisroovers Thank you both.
