### ISSUE TITLE
Alternative Installers Documentation

### ISSUE THREAD

**Issue by harens** [jorisroovers/gitlint#161]
Hi there 👋 

I thought it might be useful to document that gitlint can be downloaded by running `sudo port install gitlint` on macOS via MacPorts. Not only is this a shorter command than the homebrew version, but the homebrew formula is only on version `0.8.2` and hasn't been updated since 2017 (with the tap itself not having been updated since 2018).

You can find a summary page for your project [here](https://ports.macports.org/port/gitlint/summary), and I've already sent a PR for it to be updated to `0.14.0` https://github.com/macports/macports-ports/pull/8925. I will do my best to keep updating it since I get notified whenever you release a new version.

Let me know if you have any questions about this, and thanks for the great software!

**Comment by harens** [comment]
On the topic of Homebrew, I've sent a PR so that it can be easier to install via this method, faster to build through bottles and more up to date. https://github.com/Homebrew/homebrew-core/pull/63411.

**Comment by harens** [comment]
The PR was accepted! 🎉  Now gitlint can be installed by running the following on macOS, without the need for any 3rd party taps:

```bash
sudo port install gitlint     # MacPorts
brew install gitlint          # Homebrew
```

You might find it useful to add this to the documentation.

Since I'm the maintainer of the port on MacPorts, and this is what I have the most experience with, I'll try to update it whenever you release a new version. I cannot make the same guarantee for Homebrew (although I will try my best). However, it is possible to automate the updating process for Homebrew by using the [Bump Formula Github Action](https://github.com/marketplace/actions/homebrew-bump-formula).

**Comment by jorisroovers** [comment]
This is absolutely fantastic! 

Thank you for taking the time and signing up (best-effort) to keep them updated. Hugely appreciated 🙏

I've just updated the documentation to reflect this.

Thanks again, this made my day 😄
