### ISSUE TITLE
".venv36" not existed on vagrant VM

### ISSUE THREAD

**Issue by lukech** [jorisroovers/gitlint#167]
[**Issue symptom**] Today I cloned the repo and tried the vagrant VM with `vagrant up` followed by `vagrant ssh`. 
When logged into the VM, there's an error line printed out with regard to non-existent `.venv36` directory:
```
-bash: .venv36/bin/activate: No such file or directory
```

[**Quick analysis**] In the `Vagrantfile` there's one line that [attempts to put the virtual env activation command into .bashrc file](https://github.com/jorisroovers/gitlint/blob/92c7c4af862ff65dc9f0d5b24b4839df51582dd8/Vagrantfile#L21). However the virtual env was not actually created as part of the Vagrantfile. 

[**Env**] Though the issue feels like platform-independent, just in case it matters I spinned up the vagrant VM under a macOS 10.15.7 environment.

**Comment by lukech** [comment]
Took a further look of the `Vagrantfile`, it looks below line sets those virtual envs. 
```
./run_tests.sh --install --envs all
```
So I ran it manually on the vagrant VM, and got below errors:
```
vagrant@ubuntu-xenial:/vagrant$ ./run_tests.sh --install --envs all
### INSTALLING .venv36 (/usr/bin/python3.6) ###
AttributeError: module 'os' has no attribute 'PathLike'
./run_tests.sh: line 286: .venv36/bin/activate: No such file or directory
Traceback (most recent call last):
  File "/usr/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
Traceback (most recent call last):
  File "/usr/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```
Ran `export LC_ALL=C` solved the `unsupported locale setting` issue. 
The other `AttributeError: module 'os' has no attribute 'PathLike'` issue seems to be caused by a [recent breakage](https://github.com/pypa/virtualenv/issues/1857) to the virtualenv release 20.1.0.

**Comment by lukech** [comment]
Pinned the virtualenv module to a version prior to the breaking change solved the issue. Verified with below change to the `Vagrantfile`. 
```
sudo pip3 install virtualenv==20.0.21
```

**Comment by lukech** [comment]
Not sure if it worth a pull request, will leave to the maintainer to decide. 
In theory once virtualenv project releases a newer version with the fix, this issue is not applicable to gitlint anymore. However, it may worth having below furture-proof change anyway.
```
sudo pip3 install 'virtualenv!=20.0.22'.
```

**Comment by jorisroovers** [comment]
Hi, thanks for opening and root-causing this.

I like your suggesting of unpinning that specific version. I'll see if I can reproduce this later and if so, I can easily add the fix.

**Comment by jorisroovers** [comment]
Should be fixed on `main` branch now. I took the opportunity to upgrade the Vagrant Box to 20.04 at the same time. Appreciate if you can let me know if you end up trying this out, will otherwise close this issue soon.

**Comment by lukech** [comment]
@jorisroovers thanks for making the changes. I tried to spin up a Ubuntu 20.04 VM using the latest Vagrantfile, and it worked perfectly. I'm going to close this issue.
