### ISSUE TITLE
Body MinLength is not working properly

### ISSUE THREAD

**Issue by gernd** [jorisroovers/gitlint#17]
I have configured body length in the following way:

[body-min-length]  
min-length=5            

When I test gitlint with a commit message that is exactly 5 characters, I get the following validation error:

3: B5 Body message is too short (5<5)

Shouldn't the commit be valid, if the body consists of exactly 5 characters?

**Comment by jorisroovers** [comment]
You're absolutely right. I just looked into this and noticed that there's actually multiple bugs in the code that enforces this rule. I'll be looking into this for the 0.8.0 release which I'm hoping to find time for in the next month or two.

**Comment by jorisroovers** [comment]
Thanks again for submitting. This will go out with the 0.8.0 release which I'm planning to get out before the end of the year.

**Comment by gernd** [comment]
👍 thanks for fixing this and happy holidays
