### ISSUE TITLE
body-first-line-empty rule not working in command line

### ISSUE THREAD

**Issue by mmari7627** [jorisroovers/gitlint#175]
body-first-line-empty rule doesn't have option. It was working when using without option in gitlint configuration file but was not working in command line. 

Error Message: 
Config Error: 'body-first-line-empty' is an invalid configuration option. Use '<rule>.<option>=<value>'

**Comment by jorisroovers** [comment]
Can you please paste your full command and its output? Please use `gitlint --debug` to include debugging output as well. Thanks

**Comment by mmari7627** [comment]
Please find the command and output below. Thanks!

gitlint --debug -c title-max-length.line-length=50 -c body-first-line-empty -c body-max-line-length.line-length=72

Code: 255
STDOUT:
Config Error: 'body-first-line-empty' is an invalid configuration option. Use '<rule>.<option>=<value>'

STDERR:
DEBUG: gitlint.cli To report issues, please visit https://github.com/jorisroovers/gitlint/issues
DEBUG: gitlint.cli Platform: Linux-4.18.0-240.1.1.el8_3.x86_64-x86_64-with-redhat-8.3-Ootpa
DEBUG: gitlint.cli Python version: 3.6.8 (default, Aug 18 2020, 08:33:21) 
[GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
DEBUG: gitlint.git ('--version',)
DEBUG: gitlint.cli Git version: git version 2.27.0
DEBUG: gitlint.cli Gitlint version: 0.15.0
DEBUG: gitlint.cli GITLINT_USE_SH_LIB: [NOT SET]
DEBUG: gitlint.cli DEFAULT_ENCODING: UTF-8

**Comment by jorisroovers** [comment]
The `-c` flags are only needed if you want to change an option of a rule. `body-first-line-empty` does not have any options. Even if it did, you're not setting it correctly using `-c body-first-line-empty`, you'd need to specify the option name and value as well, but again not applicable for `body-first-line-empty`. 

This rule is enabled by default, so you don't have to specify it, you can just do:

```sh
gitlint -c title-max-length.line-length=50 -c body-max-line-length.line-length=72
```

Not sure if this answers your question to be honest, as I'm not sure what you're trying to do. Hope this helps!

**Comment by jorisroovers** [comment]
Doing some cleanup - closing this issue. Feel free to open a new issue asking to re-open this one in case you want to follow-up.
