### ISSUE TITLE
CT1: contrib-title-conventional-commits do not support the BREAKING CHANGE symbol "!"

### ISSUE THREAD

**Issue by linjiX** [jorisroovers/gitlint#186]
According to the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)

> BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:`, or appends a `!` after the type/scope, introduces a breaking API change (correlating with MAJOR in Semantic Versioning). A BREAKING CHANGE can be part of commits of any type.

> If included in the type/scope prefix, breaking changes MUST be indicated by a `!` immediately before the `:`. If ! is used, `BREAKING CHANGE:` MAY be omitted from the footer section, and the commit description SHALL be used to describe the breaking change.

But gitlint reports error if adding `!` after the scope:
```bash
$ echo 'test(scope)!: title' | gitlint --contrib=CT1 -c general.ignore=body-is-missing
1: CT1 Title does not follow ConventionalCommits.org format 'type(optional-scope): description': "test(scope)!: title"
```

**Comment by rafaelbubach** [comment]
This should solve the problem.
#190
