### ISSUE TITLE
"No commits in range" should be an error

### ISSUE THREAD

**Issue by l0b0** [jorisroovers/gitlint#193]
First, thank you for this excellent tool!

GitLab CI pipelines for "ordinary" merge requests do not include a [variable](https://gitlab.com/victor-engmark/root/-/jobs/1451078833) with the name of the target branch, which I only realised after [running `gitlint --commits "${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}..HEAD" --debug`](https://gitlab.com/victor-engmark/root/-/jobs/1451078833) and seeing it print 'DEBUG: gitlint.cli No commits in range "..HEAD"'. I suspect this is a common mistake, and that it should by default be treated as an error. There should probably also be a flag to override this, in case someone is running `gitlint` against references which could legitimately refer to an empty commit range.

As a workaround I'm going to keep running this tool in debug mode for now.

I might have time (as part of work, where we use this tool extensively) to implement the change, but I first want to make sure you agree whether this is an issue and whether it should be solved in this or some other way.

The full output:

```console
$ gitlint --commits "${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}..HEAD" --debug
DEBUG: gitlint.cli To report issues, please visit https://github.com/jorisroovers/gitlint/issues
DEBUG: gitlint.cli Platform: Linux-5.4.109+-x86_64-with-debian-10.10
DEBUG: gitlint.cli Python version: 3.7.3 (default, Jan 22 2021, 20:04:44) 
[GCC 8.3.0]
DEBUG: gitlint.git ('--version',)
DEBUG: gitlint.cli Git version: git version 2.20.1
DEBUG: gitlint.cli Gitlint version: 0.15.0
DEBUG: gitlint.cli GITLINT_USE_SH_LIB: [NOT SET]
DEBUG: gitlint.cli DEFAULT_ENCODING: UTF-8
DEBUG: gitlint.cli Configuration
config-path: /builds/victor-engmark/root/.gitlint
[GENERAL]
extra-path: None
contrib: ['contrib-title-conventional-commits']
ignore: body-is-missing
ignore-merge-commits: True
ignore-fixup-commits: True
ignore-squash-commits: True
ignore-revert-commits: True
ignore-stdin: False
staged: False
verbosity: 3
debug: True
target: /builds/victor-engmark/root
[RULES]
  I1: ignore-by-title
     ignore=all
     regex=None
  I2: ignore-by-body
     ignore=all
     regex=None
  I3: ignore-body-lines
     regex=None
  T1: title-max-length
     line-length=72
  T2: title-trailing-whitespace
  T6: title-leading-whitespace
  T3: title-trailing-punctuation
  T4: title-hard-tab
  T5: title-must-not-contain-word
     words=WIP
  T7: title-match-regex
     regex=None
  T8: title-min-length
     min-length=5
  B1: body-max-line-length
     line-length=80
  B5: body-min-length
     min-length=20
  B6: body-is-missing
     ignore-merge-commits=True
  B2: body-trailing-whitespace
  B3: body-hard-tab
  B4: body-first-line-empty
  B7: body-changed-file-mention
     files=
  B8: body-match-regex
     regex=None
  M1: author-valid-email
     regex=[^@ ]+@[^@ ]+\.[^@ ]+
  CT1: contrib-title-conventional-commits
     types=build,chore,ci,docs,feat,fix,perf,refactor,revert,style,test
DEBUG: gitlint.cli No --msg-filename flag, no or empty data passed to stdin. Using the local repo.
DEBUG: gitlint.git ('rev-list', '..HEAD')
DEBUG: gitlint.cli No commits in range "..HEAD"
```

**Comment by sigmavirus24** [comment]
Not the maintainer, but I could see that this would be helpful to have as an flag, e.g., `--require-commits` or `--fail-without-commits`. I'm not certain this should fail always. (Just trying to point out another path to your goal)

**Comment by jorisroovers** [comment]
I'm always hesitant to change default behavior, as it tends to break gitlint for others.
I like @sigmavirus24's suggestion to add a flag for this. My preference goes towards `--fail-without-commits`, as this allows for more such flags in the future that follow the same `--fail-<condition>` pattern.

Appreciate your help :-) Please do take a moment to read through the [contributing](https://jorisroovers.com/gitlint/contributing/) docs before you start. Thanks!
