### ISSUE TITLE
Allow ignoring commits from specific author

### ISSUE THREAD

**Issue by wwuck** [jorisroovers/gitlint#216]
It would be nice to have a configuration option to ignore commits from a specific commit author.

I have gitlint configured to require a commit message body.  I have just started to use [Renovate Bot](https://docs.renovatebot.com/) with the [semantic commit messages](https://docs.renovatebot.com/semantic-commits/) enabled.  Unfortunately renovate by default only includes the title in the commit message and leaves out the commit body, at least for the autogenerated onboarding PR.  This has necessitated ignoring the missing commit body in gitlint configuration.

This would be easy to solve if there was a configuration option to ignore all commits from the renovate-bot author.

**Comment by sigmavirus24** [comment]
I know Whitesource's reputation, so I doubt it's willing to help here, but their bot is open source: https://github.com/renovatebot/renovate would it not be possible to improve this for everyone by including better commit messages rather than lowering standards?

**Comment by wwuck** [comment]
Ahhh thanks for the hint. I had searched through the docs but missed this.

https://docs.renovatebot.com/self-hosted-configuration/#onboardingcommitmessage

I’ll close this issue now.
