### ISSUE TITLE
Pre-commit Hook Crashes When Commit Aborted

### ISSUE THREAD

**Issue by Kurt-von-Laven** [jorisroovers/gitlint#218]
gitlint is a commit-msg hook, so [pre-commit follows git's lead and calls it when the commit message is empty](https://github.com/pre-commit/pre-commit/issues/2052). This leads to the following error:

```
gitlint.......................................................................Failed
- hook id: gitlint
- exit code: 2

1: T8 Title is too short (0<5)
3: B6 Body message is missing
```

**Comment by jorisroovers** [comment]
That's not a crash, gitlint is failing because you've got violations in your commit message, i.e. an empty commit message. 
If you want gitlint to pass this, you can configure it to ignore rule T8 and B6. In `.gitlint`:

```ini
[general]
# Ignore certain rules (comma-separated list), you can reference them by their
# id or by their full name
ignore=T8,B6
```

**Comment by Kurt-von-Laven** [comment]
Indeed; apologies for the sloppy terminology. I could certainly suppress the error, but the drawback would be that it wouldn't catch those errors when someone is actually committing. An empty commit message is a special case since the commit isn't going through anyways, so it would ideally be handled specially. I would be open to submitting a pull request if not linting empty commit messages would be of interest.

**Comment by sigmavirus24** [comment]
From the linked issue on pre-commit, would it be fair to say that you'd rather `gitlint` run on the `prepare-commit-msg` stage rather than the `commit-msg` stage?

Looking at the documentation from Git itself, I don't think that's feasible or correct:

> The prepare-commit-msg hook is run before the commit message editor is fired up but after the default message is created. It lets you edit the default message before the commit author sees it. This hook takes a few parameters: the path to the file that holds the commit message so far, the type of commit, and the commit SHA-1 if this is an amended commit. This hook generally isn’t useful for normal commits; rather, it’s good for commits where the default message is auto-generated, such as templated commit messages, merge commits, squashed commits, and amended commits. You may use it in conjunction with a commit template to programmatically insert information.
> 
> The commit-msg hook takes one parameter, which again is the path to a temporary file that contains the commit message written by the developer. If this script exits non-zero, Git aborts the commit process, so you can use it to validate your project state or commit message before allowing a commit to go through. In the last section of this chapter, we’ll demonstrate using this hook to check that your commit message is conformant to a required pattern.
> 
> After the entire commit process is completed, the post-commit hook runs. It doesn’t take any parameters, but you can easily get the last commit by running git log -1 HEAD. Generally, this script is used for notification or something similar.

From https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks

---

I don't know that we want to special case empty commit messages. If I _just_ use gitlint, I don't really have issues with the `commit-msg` hook

```
 ~  mkdir tmp
 ~  cd tmp
 ~/tmp  ls
 ~/tmp  git init
Initialized empty Git repository in /home/sigmavirus24/tmp/.git/
 ~/tmp > on main  pipx install gitlint
  installed package gitlint 0.15.1, Python 3.9.7
  These apps are now globally available
    - gitlint
done! ✨ 🌟 ✨
 ~/tmp > on main  gitlint install-hook
Successfully installed gitlint commit-msg hook in /home/sigmavirus24/tmp/.git/hooks/commit-msg
 ~/tmp > on main  touch README.rst
~/tmp > on main +1  git commit -m 'Initial Commit' -n 
[main (root-commit) 19f39f8] Initial Commit
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 README.rst
 ~/tmp > on main  git mv README.rst README
gitlint: checking commit message...
1: T8 Title is too short (0<5)
3: B6 Body message is missing
-----------------------------------------------
gitlint: Your commit message contains violations.
Continue with commit anyways (this keeps the current commit message)? [y(es)/n(no)/e(dit)] y
Aborting commit due to empty commit message.
```

Note that

```
Continue with commit anyways (this keeps the current commit message)? [y(es)/n(no)/e(dit)] y
Aborting commit due to empty commit message.
```

Come from `git` not from `gitlint`. The other part of this is that `git-commit` has `--allow-empty-message` as a flag. So it's entirely plausible that someone could run `git commit --allow-empty-message --no-edit` and in that case, `gitlint` should _absolutely_ fail. If `gitlint` had a flag that said `--allow-empty-message` assuming that's used to allow folks to abort, I don't think it would achieve what was desired in every case

**Comment by Kurt-von-Laven** [comment]
> From the linked issue on pre-commit, would it be fair to say that you'd rather gitlint run on the prepare-commit-msg stage rather than the commit-msg stage?

No, definitely not. I meant the following excerpt from the linked issue in reference only to the case raised there of commit-msg hooks being misused to generate commit messages.

> Of course, but that would be better done as a prepare-commit-msg hook instead so that the developer retains the option to abort the commit. It would be a bit startling to join a project configured to replace empty with non-empty commits.

I don't see a distinction between the use of gitlint within the pre-commit framework and run independently. gitlint also outputs the following when used within the pre-commit framework in the case of an aborted commit:
```
gitlint: checking commit message...
1: T8 Title is too short (0<5)
3: B6 Body message is missing
```

I would argue this is not the best action to take when the commit has already been aborted. When you abort a commit while using commit-msg hooks within the pre-commit framework, you get hit with a storm of misleading error output from many hooks. These sorts of minor issues are easily ignored by most experienced developers, but as a teacher/mentor I have noticed that newcomers (who are generally the least likely to write correct commit messages and the most likely to directly benefit from a tool like gitlint) are often heavily disoriented by output like this. They typically still have a little too much faith in what their computer tells them (if they don't have the opposite struggle of routinely overlooking error output), and can easily lose hours debugging issues that never existed.

> So it's entirely plausible that someone could run `git commit --allow-empty-message --no-edit` and in that case, gitlint should *absolutely* fail.

That's an interesting point. Personally, I would rather that gitlint interpret the use of `--allow-empty-message` to also mean that gitlint should be suppressed (essentially like `--no-verify` in this context), but I see how subjective that is. Do you respect the will of the end developer or the developer who configured the hook in that case? My argument for accepting the empty message is that the maintainer should control their CI, which can straightforwardly run all pre-commit hooks, and the end developer should ultimately control what they do on their own computer. I do feel that Git itself should only be calling commit-msg hooks with empty commit messages when `--allow-empty-message` is used, which would make it possible to operate differently in the two cases, so I could certainly see the argument for closing this issue until Git's behavior changes. I have been emailing with Git maintainers about changing when commit-msg is called, but since they don't use a browser-based issue tracker, I unfortunately can't link to that conversation. I'll update with their thoughts once the dust settles, but the fact that commit-msg hooks presently don't know which scenario they are in when the message is empty is a helpful contribution to that discussion, so thank you.

**Comment by sigmavirus24** [comment]
> I meant the following excerpt from the linked issue in reference only to the case raised there of commit-msg hooks being misused to generate commit messages.

It's not misused. That's a documented feature in the git docs.

> I don't see a distinction between the use of gitlint within the pre-commit framework and run independently. gitlint also outputs the following when used within the pre-commit framework in the case of an aborted commit:

Correct except that the commit _hasn't_ been aborted. That was my point. Please look closely at the output:

```
 ~/tmp > on main  git mv README.rst README
gitlint: checking commit message...
1: T8 Title is too short (0<5)
3: B6 Body message is missing
-----------------------------------------------
gitlint: Your commit message contains violations.
Continue with commit anyways (this keeps the current commit message)? [y(es)/n(no)/e(dit)] y
Aborting commit due to empty commit message.
```

> as a teacher/mentor I have noticed that newcomers (who are generally the least likely to write correct commit messages and the most likely to directly benefit from a tool like gitlint) are often heavily disoriented by output like this.

I think this is exactly the reason beginners _shouldn't_ use a tool like gitlint. If you're forcing this on someone new, they haven't understood the _why_ and now they're being confused when something goes awry and trying to satisfy a machine neither of which are instructive.

> That's an interesting point. Personally, I would rather that gitlint interpret the use of `--allow-empty-message` to also mean that gitlint should be suppressed (essentially like `--no-verify` in this context), but I see how subjective that is.

Except that `--allow-empty-message` doesn't imply `--no-verify` but those are both options someone can specify. And further `gitlint` doesn't have access to the parameters that were provided to git. How could we possibly guess a developers intention, even if we did?

>  Do you respect the will of the end developer or the developer who configured the hook in that case?

Are they not the same person? If the developer is part of a team using gitlint to improve the quality of messages - they've agreed to do so. No one in any environment (open source or corporate) would ever believe that an empty commit message provided any value. If they did believe that, they probably wouldn't have ever agreed to use `gitlint`.

> My argument for accepting the empty message is that the maintainer should control their CI, which can straightforwardly run all pre-commit hooks, and the end developer should ultimately control what they do on their own computer.

I don't understand this in the slightest. You're arguing that people should be able to create empty commit messages when a project has it as part of it's contribution guidelines that the message follow a format/style guide and be valuable in order to be accepted? You're arguing that person waste time contributing to have machines tell them later what they did wrong when they could have used a tool like `pre-commit` to find that out quite immediately?

> I do feel that Git itself should only be calling commit-msg hooks with empty commit messages when `--allow-empty-message` is used, which would make it possible to operate differently in the two cases, so I could certainly see the argument for closing this issue until Git's behavior changes. I have been emailing with Git maintainers about changing when commit-msg is called, but since they don't use a browser-based issue tracker, I unfortunately can't link to that conversation. I'll update with their thoughts once the dust settles, but the fact that commit-msg hooks presently don't know which scenario they are in when the message is empty is a helpful contribution to that discussion, so thank you.

I doubt Git will change. I could see them adding an additional hook potentially, but one of the explicitly stated user goals mentioned in the documentation above is that this can modify the message (either to include something generated or correct/remove something). It would likely be a surprising and severely incompatible change for git to change that behaviour.

**Comment by Kurt-von-Laven** [comment]
> It's not misused. That's a documented feature in the git docs.

To clarify, I don't mean that a commit-msg hook should never modify a commit message. [sign-commit](https://github.com/mattlqx/pre-commit-sign) is a good example of such a hook as it appends to an existing commit message. What I find less compelling is the use of a commit-msg hook (rather than a commit message template or a prepare-commit-msg hook) to generate a default commit message.

> Correct except that the commit _hasn't_ been aborted. That was my point. Please look closely at the output:
> 
> ```
>  ~/tmp > on main  git mv README.rst README
> gitlint: checking commit message...
> 1: T8 Title is too short (0<5)
> 3: B6 Body message is missing
> -----------------------------------------------
> gitlint: Your commit message contains violations.
> Continue with commit anyways (this keeps the current commit message)? [y(es)/n(no)/e(dit)] y
> Aborting commit due to empty commit message.
> ```

I get what you are saying here that the commit hasn't been aborted in a physical sense at this point. What I meant more precisely was that the developer has already requested that the commit be aborted. The prompt to continue with the commit anyways is pertinent to the developer's intent here, but message from gitlint is not.

> I think this is exactly the reason beginners _shouldn't_ use a tool like gitlint. If you're forcing this on someone new, they haven't understood the _why_ and now they're being confused when something goes awry and trying to satisfy a machine neither of which are instructive.

I'm not, no, but I certainly agree that wiring up tools without explaining their purpose tends to go awry exactly as you say. If beginner-friendliness is a non-goal, everything we have been discussing is moot, but I see gitlint as having a lot to offer folks who are new to open-source world when explained clearly.

> Except that `--allow-empty-message` doesn't imply `--no-verify` but those are both options someone can specify. And further `gitlint` doesn't have access to the parameters that were provided to git. How could we possibly guess a developers intention, even if we did?

For sure someone who is more familiar with Git will not be stumped by the need to tack `--no-verify` on there as well, and I agree that using `--allow-empty-message` without `--no-verify` when gitlint is enabled sends mixed messages. I am merely saying that a developer who passed `--allow-empty-message` but not `--no-verify` likely wouldn't be surprised or disappointed when gitlint accepted their empty commit message. The most likely reason I can think of that an end developer would do that is with the intent of suppressing error messages but not the awareness of `--no-verify`, particularly since I suspect that in relative terms very few Git users have this awareness. If they then made the mistake of pushing that commit, hopefully it would fail CI anyways. Like you say though, it's broadly understood that empty commit messages are not constructive or desirable, and yet they have just used a flag intended to override an obvious error, so their purpose is probably purely local and physical. For example, they might be dropping some but not all of their work in progress, rebasing, creating a revert of a portion of work to subsequently apply during a rebase, splitting work into named branches, switching branches when their stash is already overused or without awareness of stashing, and/or anticipating subsequently rewriting and/or squashing their commits anyways. I am aware that gitlint does not have access to the parameters passed to Git. If, however, it is acceptable for gitlint to do nothing when the end developer has asked to allow an empty message, then regardless of whether an empty commit message is to be allowed or aborted, gitlint could reasonably exit silently and successfully.

> Are they not the same person? If the developer is part of a team using gitlint to improve the quality of messages - they've agreed to do so. No one in any environment (open source or corporate) would ever believe that an empty commit message provided any value. If they did believe that, they probably wouldn't have ever agreed to use `gitlint`.

I don't mean to imply gitlint would be such a tool, but many developers are asked to use tools they don't want to. In the open-source world, I would tend to expect that gitlint had been configured by a maintainer primarily to catch mistakes made by contributors, who may not even be aware which tools the project uses (or that commit hooks exist for that matter).

> I doubt Git will change. I could see them adding an additional hook potentially, but one of the explicitly stated user goals mentioned in the documentation above is that this can modify the message (either to include something generated or correct/remove something). It would likely be a surprising and severely incompatible change for git to change that behaviour.

We may already be on the same page about this, but to be clear, I'm not asking the Git maintainers to remove the capacity to modify messages from commit-msg hooks. (Actually, one respondent threw out this idea in passing, and I offered sign-commit as an example of why such a change would not be desirable.) I did mention the possibility of an additional hook, and there has been a little discussion around backwards compatibility so far. I do share the backwards compatibility concern, and I'm definitely not suggesting such a change be rammed through quickly.

**Comment by sigmavirus24** [comment]
> I get what you are saying here that the commit hasn't been aborted in a physical sense at this point.

There's no possible way for us to detect that it has been aborted. Your point is moot.

> If beginner-friendliness is a non-goal

I didn't say it was a non-goal. I said "mentors" who force tooling on people such that the tooling teaches them a lesson, are doing those people a disservice especially as those people are being taught to satisfy technology rather than understand the value of what they're doing to satisfy that technology.

> If, however, it is acceptable for gitlint to do nothing when the end developer has asked to allow an empty message

And here is where we disagree. Because you're inventing reasons why someone might do this instead of actually using the tool (git in this case) the way it was designed.

> contributors, who may not even be aware which tools the project uses (or that commit hooks exist for that matter).

So you're arguing for contributors to have to put in the least possible effort by not reading documentation written by maintainers that tends to explain these things or looking at prior pull requests to the project to determine what's expected of them? You're arguing that tooling designed to keep contributions valuable be altered to allow low-quality, low-effort contributions? I'm very confused here. I think you need to take a step back and look at what you're arguing because I don't believe that you even actually believe yourself at this point.

**Comment by Kurt-von-Laven** [comment]
> There's no possible way for us to detect that it has been aborted. Your point is moot.

This is an important context to consider, but the two cases can be handled the same way, by silently succeeding. In the case of an aborted commit, the commit would be aborted anyway (and with a cleaner user experience) by Git. In the case of `--allow-empty-message`, the empty message would be allowed, which does not seem like such a terrible thing to me. The vast majority of the time an empty message corresponds to the first case. I'm not saying that it absolutely never happens, but not once in my entire life have I seen anyone push an empty commit message (even to a branch they didn't intend for anyone to read). It is not even possible to have the opportunity to do so without first consciously overriding an existing safety measure, which is equivalent to all the protection gitlint ever can and should provide.

> I didn't say it was a non-goal. I said "mentors" who force tooling on people such that the tooling teaches them a lesson, are doing those people a disservice especially as those people are being taught to satisfy technology rather than understand the value of what they're doing to satisfy that technology.

I agree with this point, and as I said I'm not forcing gitlint on beginners. I was referring to this line:

> I think this is exactly the reason beginners *shouldn't* use a tool like gitlint.

> And here is where we disagree. Because you're inventing reasons why someone might do this instead of actually using the tool (git in this case) the way it was designed.

I appreciate the value of following specs and consistency with design intention, but I don't believe there is a carefully considered design intention for how commit-msg hooks ought to handle empty commit messages. If there were, commit-msg hooks would presumably at least be given some mechanism by which to distinguish the `--allow-empty-message` case from the "empty message means abort" case. The alternative to assuming the user doesn't intend to push the commit isn't making no assumptions, but rather assuming they do intend to push it. An assumption must be made, and accurately inferring user intent is one of the defining hallmarks of user-friendly software. I wish I could claim to have invented fundamental principles of user design and psychology, but I am merely applying what others have taught me.

> So you're arguing for contributors to have to put in the least possible effort by not reading documentation written by maintainers that tends to explain these things or looking at prior pull requests to the project to determine what's expected of them? You're arguing that tooling designed to keep contributions valuable be altered to allow low-quality, low-effort contributions? I'm very confused here. I think you need to take a step back and look at what you're arguing because I don't believe that you even actually believe yourself at this point.

I most certainly do believe myself. I don't think anyone sanely advocates for ignorance or apathy, so of course we agree that contributors should do all the things that you and I already know contributors should do. We both also know the reality is that doesn't always happen, and share the belief that tools like gitlint help address this problem. Even beginners don't push empty commit messages to branches intended for review. This simply doesn't happen in appreciable numbers at any experience level. At the end of the day, I'm simply arguing for gitlint not to output an error message in a case where no error was made (either because the end developer aborted the commit or explicitly requested an override).
