### ISSUE TITLE
Ability to specify user rules as a file instead of directory

### ISSUE THREAD

**Issue by tommyip** [jorisroovers/gitlint#26]
Currently gitlint can only take a directory as argument for extra rules `gitlint --extra-path=<path>`, would it make sense to also support only filenames?

**Comment by jorisroovers** [comment]
Yes, we could support a single filename or a list of comma-separated filenames as well. Maybe something for a future release. 

FWIW, gitlint will only load actual rule classes in the ```extra-path```, all non-python files are ignored, as are all classes that don't extend from ```LineRule``` or ```CommitRule```, see here:
http://jorisroovers.github.io/gitlint/user_defined_rules/#rule-requirements

**Comment by tommyip** [comment]
Working on this.

**Comment by jorisroovers** [comment]
Awesome @tommyip. FYI that I'll be rather busy for the next 1-2 months and am not sure whether I'll be able to find a lot of time to review or bring out a new release. I'll try, but it's likely that there will be significant delays. Thanks for understanding :)

**Comment by tommyip** [comment]
No problem! This is not super important or anything, just a nice to have feature.

**Comment by jorisroovers** [comment]
Ok, did manage to make some time right now :) Merged this, will be releasing 0.8.2 today, mostly to deal with #27 (duplicate #30) but this PR will also be part of it :)
