### ISSUE TITLE
`--commits` doesn't aggregate the return code

### ISSUE THREAD

**Issue by AlexMooney** [jorisroovers/gitlint#30]
When running `gitlint --commits $REFS` where `$REFS` is a range of hashes, the program returns an exit status corresponding to the final commit in the range and ignores any earlier errors encountered.

**Comment by jorisroovers** [comment]
This is a duplicate of https://github.com/jorisroovers/gitlint/issues/27 which has already been fixed, just not released. I acknowledge this is a rather important issue, so will release 0.8.2 with this fix today.

Closing this defect.
