### ISSUE TITLE
[feature] Support shell completion

### ISSUE THREAD

**Issue by Freed-Wu** [jorisroovers/gitlint#344]
Use <https://docs.iterative.ai/shtab/> as an extra requirement, like <https://github.com/andreafrancia/trash-cli/blob/master/trashcli/shell_completion.py>?

Thanks.

**Comment by Freed-Wu** [comment]
Thanks, I found it. I suggest it should be added to `README.md` to let more people know :smile:

```sh
_GITLINT_COMPLETE=zsh_source gitlint |sudo tee /usr/share/zsh/site-functions/_gitlint
```

**Comment by jorisroovers** [comment]
While I had thought about shell completion before, I didn't actually know Click supported this out of the box like that :-) 
Let me keep this ticket open to update our docs!
