### ISSUE TITLE
[feature] Support PEP621

### ISSUE THREAD

**Issue by Freed-Wu** [jorisroovers/gitlint#380]
According to <https://peps.python.org/pep-0621>, any python project should
store its metadata in `pyproject.toml`, not `.gitlint`, `.yamllint.yaml`, `.vintrc.yml`, `addon-info.json`, or other thing.

Many projects have support PEP621, such as

- <https://github.com/psf/black>
- <https://github.com/codespell-project/codespell>
- <https://github.com/PyCQA/pydocstyle>
- <https://github.com/pypa/setuptools>
- <https://github.com/pypa/setuptools_scm/>
- <https://github.com/pypa/hatch>
- <https://github.com/pypa/flit>
- <https://github.com/python-poetry/poetry>
- ...

So I advise this project can support, too.

Before python3.11, toml support must be provided by third-party package, such as

- <https://github.com/psf/black>: [tomli](https://github.com/psf/black/blob/main/pyproject.toml#L70)
- <https://github.com/codespell-project/codespell>: [tomli](https://github.com/codespell-project/codespell/blob/master/pyproject.toml#L46)
- <https://github.com/PyCQA/pydocstyle>: [toml](https://github.com/PyCQA/pydocstyle/blob/master/setup.py#L11)
- <https://github.com/pypa/setuptools>: [tomli, tomli-w, ini2toml](https://github.com/pypa/setuptools/blob/main/setup.cfg#L72-L81)
- <https://github.com/pypa/setuptools_scm/>: [tomli](https://github.com/pypa/setuptools_scm/blob/main/setup.cfg#L35)
- <https://github.com/pypa/hatch>: [tomli-w, tomlkit](https://github.com/pypa/hatch/blob/master/pyproject.toml#L52-L53)
- <https://github.com/pypa/flit>: [tomli](https://github.com/pypa/flit/blob/main/pyproject.toml#L32)
- <https://github.com/python-poetry/poetry> [tomli, tomlkit](https://github.com/python-poetry/poetry/blob/master/pyproject.toml#L70-L72)
- ...

You can use one as extras_require.

After python3.11, tomllib is a builtin package. Not need install any toml package. Remember `python<3.11` in requirements.txt

**Comment by sigmavirus24** [comment]
> According to https://peps.python.org/pep-0621, any python project should
store its metadata in pyproject.toml, not .gitlint, .yamllint.yaml, .vintrc.yml, addon-info.json, or other thing.

This is incredibly disingenuous or possibly just a severe misreading of that PEP.

It talks about the format to use _if_ one stores **core** metadata (in other words, build system related metadata) about a project. It provides allowance for non-core systems to store metadata there - an affordance regretted by many involved in that PEP.

It does not require projects to support it.

Further, gitlint has many issues on/relating to this topic which explain very clearly why gitlint's config will not be read from `pyproject.toml`

**Comment by Freed-Wu** [comment]
Oh, its my fault, it should be <https://peps.python.org/pep-0518/#tool-table> (right, pep only have a number which make it is hard to remember), It suggests every python tool store their setting to `pyproject.toml`s `tool`, that is

```python
[tool.gitlint]
ignore-by-title = { regex=".*", ignore=body-is-missing }
```

> This is incredibly disingenuous

I am sorry without offense.

**Comment by Freed-Wu** [comment]
And search PEP518, it has a same issue <https://github.com/jorisroovers/gitlint/issues/115>, so it is repeated. Close.

**Comment by sigmavirus24** [comment]
To be clear, because you still seem to think the PEPs require support - there is no requirement that tools place configuration there. They merely provide support for naming conventions for sections that tools might use _if_ they want to allow configuration in that file.

There is no requirement or imperative to do so
