### ISSUE TITLE
[QUESTION] Is it possible to check for the total commit message length instead of just line length?  

### ISSUE THREAD

**Issue by ericriff** [jorisroovers/gitlint#393]
We recently ended up with an automated commit with 61K lines of text. Looking to prevent that from happening again, I came across this wonderful tool.

I see that there are options to limit the title length and line length, but I don't see if it is possible to check for the total length of the commit message. Is this possible?

Thanks!

Eric.

**Comment by sigmavirus24** [comment]
You could do that with your own -defined rule: https://jorisroovers.com/gitlint/user_defined_rules/
