### ISSUE TITLE
gitlint </dev/null "fails" (as not sys.stdin.isatty())

### ISSUE THREAD

**Issue by domo141** [jorisroovers/gitlint#40]
```
$ gitlint

$ gitlint </dev/null
1: UC2 Body does not contain a 'Signed-Off-By' line
1: UC3 Title does not follow <subsystem>: <subject>
3: B6 Body message is missing
```

There are many cases (e.g. automated checks) where stdio is not attached to tty (and e.g. --commits is to be used), where it would be nice that this worked; current workaround is `script -ec 'gitlint'` (works when linux script(1) is new enough to know -e option).

Looks like current HEAD (b054219ef6) has some changes which shows where this problem occurs, it looks these changes do not fix this issue.

**Comment by jorisroovers** [comment]
I'll need to look into this - not sure when I'll find the time though (might take a while). Marking as enhancement.
