### ISSUE TITLE
Release new version to PyPI

### ISSUE THREAD

**Issue by srstevenson** [jorisroovers/gitlint#41]
Thanks for writing gitlint @jorisroovers, it's really helpful! Are there any blockers to releasing 0.9.0 to PyPI? I have `commit.verbose = true` set in my global Git configuration, so it would be great to have a new release that includes the changes merged in #34.

**Comment by jorisroovers** [comment]
Thanks, I think I needed the nudge :) I've been putting this off for months - life and other projects have been getting in the way. 

I just need to finish up https://github.com/jorisroovers/gitlint/tree/issues/33 which IIRC is just writing some tests and can then probably roll a new release. I'll try to do so this weekend. Keep me honest :-)

**Comment by jorisroovers** [comment]
Released :) https://github.com/jorisroovers/gitlint/releases/tag/v0.9.0

Also pushed latest version to pypi. Closing this out!

**Comment by srstevenson** [comment]
Thanks!
