### ISSUE TITLE
Forever violations even after being edited

### ISSUE THREAD

**Issue by 5ouma** [jorisroovers/gitlint#536]
Even if I edit the warned commit message via `e(dit)`, it outputs the same warning.
I use Gitlint as `gitlint --target='/path/to/repo' install-hook` to set the `commit-msg` hook globally with `hooksPath = ~/.config/git/hooks`.

I think this is because it doesn't read the commit message after edited.

**Comment by sigmavirus24** [comment]
Duplicate of #180 potentially.

Please ensure you're on the latest version and provide more information to help debug this

**Comment by 5ouma** [comment]
Yes, you're right.
I used v0.19.1 **the latest version** for GitHub releases. If it's possible, please make a release to become able to install via Homebrew.

I'm looking forward to it being released v0.20.0 as soon as possible.
Over 7 months have passed since @jorisroovers opened #462. (I know they didn't promise though.)

**Comment by 5ouma** [comment]
I'm looking forward to it being released v0.20.0 as soon as possible.
Over 7 months have passed since you opened #462. (I know you didn't promise though.)
