### ISSUE TITLE
Ignoring commits based on rules

### ISSUE THREAD

**Issue by kiov** [jorisroovers/gitlint#54]
There are plans to add some sort of rule based commit ignoring?

We are using [maven](https://maven.apache.org/) and the release precess add commits with messages like:

    [maven-release-plugin] prepare for next development iteration

Or

    [maven-release-plugin] prepare release <tag>

I can modify maven configuration to include a `gitlint-ignore: all` but thats really not the best solution IMO.

The idea was something in the line of author, title or body ignore rule, if the commit match that rule then is not processed.

**Comment by jorisroovers** [comment]
> I can modify maven configuration to include a gitlint-ignore: all but thats really not the best solution IMO

Agreed that this isn't the ideal solution.

I'll tag this as an enhancement, but just FYI that I don't think I'll be able to work on this for a while (think months). 

Potential workaround is to put gitlint in a bash script and just do some bash magic (untested, probably buggy):
```bash
#!/bin/bash
set -e # fail on error, needed for the script to skip gitlint for maven messages

MESSAGE=$(git log -1 --pretty=%B)
echo "$MESSAGE" | grep -v "[maven-release-plugin] prepare release"
echo "$MESSAGE" | grep -v "[maven-release-plugin] something else to ignore"
echo "$MESSAGE" | grep -v "[maven-release-plugin] ignoring more"
echo "$MESSAGE" | gitlint
```

**Comment by jorisroovers** [comment]
FYI that there's some work going on related to this: https://github.com/jorisroovers/gitlint/pull/57

No ETA on when this will land.
