### ISSUE TITLE
Force using repo via command line option

### ISSUE THREAD

**Issue by pbregener** [jorisroovers/gitlint#56]
As discussed in #42 and #52, there seem to be problems with the automatic check for data passed in via STDIN and the fallback to using the local repo. As it appears hard to fix, and some of the proposed (and implemented) fixes only fix the problem for certain CI configurations, I would suggest to add a command line option `--use-repo` (and/or a config file flag) that forces the use of the local repo and ignores any data from STDIN. This would  make use in any CI environment and configuration (however proven or obscure that particular one might be) much easier and fool-proof.

This seems like a boring and simple solution to an apparent otherwise difficult-to-solve problem (see above linked issue).

What do you think @jorisroovers?

**Comment by jorisroovers** [comment]
Yeah, I agree, but would suggest to call it ```--force-local-repo```. Happy to accept .

FWIW, looking at #42  and #52  is a top of mind when I find some proper time to work on gitlint (maybe this weekend?).

**Comment by pbregener** [comment]
As I just wrote in https://github.com/jorisroovers/gitlint/issues/42#issuecomment-377246266, I'm using a pretty ugly but effective workaround right now. I might try to come up with a PR for this, but on the other hand this will be unnecessary if we can get the STDIN check to work properly.

**Comment by jorisroovers** [comment]
I just saw that, pretty clever workaround :-)

I just started looking into #42 and #52 again and am able to reproduce in Jenkins. The fix from #52  doesn't seem to work, but need to spend more time on it - probably later today or tomorrow.

**Comment by pbregener** [comment]
Will be happy to try other approaches in GitLab CI. Just ping me if you have something that's ready for testing :)
