### ISSUE TITLE
Add support for multiple ignore-* rules in configuration file

### ISSUE THREAD

**Issue by jmaupetit** [jorisroovers/gitlint#66]
Hi there :wave: Thank you for providing this amazing project to the community!

I recently stumbled upon a disturbing issue: we cannot define multiple `ignore-by-title` sections in the `.gitlint` configuration. It means that I cannot define different rules to ignore given a particular regex.

Did I missed something?
Is this a limitation of the ini/cfg format?

**Comment by jmaupetit** [comment]
Thank you for your quick answer @jorisroovers! I came to the same conclusion and used a more complex regex. But doing so exclude the possibility to ignore a specific rule for a particular regexp: we are constraint to ignore an aggregation of all rules we want to ignore.

As I am using YAML a lot these days, I think switching the configuration to this file format would add more flexibility. But it's a huge refactoring...

**Comment by jorisroovers** [comment]
Unfortunately YAML alone wouldn't fix this, it also has to do with how gitlint stores rules internally (only 1 instance of each rule can be active at once).

I don't think we necessarily need to support multiple of the same rules though.
I believe what we need is to allow users to add a mapping in the ignore rule that allows them to specify multiple regexes to be mapped to different lists of rules to ignore.

For example:
```ini
[ignore-by-title]
regex1=<regex1>
ignore1=title-max-length,body-min-length
regex2=<regex2>
ignore2=all
```

While I agree that we YAML would allow us to do this using nicer syntax, I think these number-based ```(regexN, ignoreN)``` tuples are an acceptable trade-off.

For backwards compatibility we'd just internally map ```regex, ignore``` to ```regex1,ignore1```.

Interested to hear your thoughts :-)

(Again, probably won't actually work on this for a while, but definitely something I'll consider doing at some point.)

**Comment by jmaupetit** [comment]
> it also has to do with how gitlint stores rules internally (only 1 instance of each rule can be active at once).

True, that why I've said that it would be deep refactoring.

I like your proposal, let's do this!

Nothing hurries, let's keep in touch and keep up the good work! :muscle:

**Comment by jorisroovers** [comment]
2+ years later...

I just implemented 'Named Rules' which allows users to have multiple of the same rule active at the same time, like so:

```ini
# .gitlint file

[ignore-by-title:first-instance]
regex=(.*)ignore(.*)
ignore=all

[ignore-by-title:second-instance]
regex=(.*)foobar(.*)
ignore=B6

[ignore-by-title:thisCanReallyBeWhateverYouWant]
regex=(.*)hurdur(.*)
ignore=T2,T3
```

Of course it's possible to create conflicting rules this way, but that's up to the user to make sure that doesn't happen.

This should solve this use-case :) This will go out as part of 0.14, somewhere in next few weeks.
