### ISSUE TITLE
Can't use install-hooks in with git worktree

### ISSUE THREAD

**Issue by jpulec** [jorisroovers/gitlint#68]
Because of https://github.com/jorisroovers/gitlint/blob/master/gitlint/hooks.py#L7 being hard-coded as `.git/hooks`, the `install-hooks` command doesn't seem to work when using git worktrees. Worktrees keep all of their hooks in the main repository folder.

**Comment by rico-chet** [comment]
That variable should probably be result of `git rev-parse --git-path hooks`

**Comment by jorisroovers** [comment]
Sounds reasonable :) Will add this to the TODO list. No ETA on when I'll get to this (probably a few months, life get's busy...). Happy to accept PRs!
