### ISSUE TITLE
Gitlint looks at changed files when installed through pre-commit

### ISSUE THREAD

**Issue by pzelnip** [jorisroovers/gitlint#75]
Following the [docs](https://jorisroovers.github.io/gitlint/#using-gitlint-through-pre-commit), in my .pre-commit-config.yaml I have:

```
-   repo: https://github.com/jorisroovers/gitlint
    rev:  master
    hooks:
    -   id: gitlint
```
Upon doing a ```git commit -a``` I get: 

```
 λ git commit -a
[INFO] Initializing environment for https://github.com/jorisroovers/gitlint.
[INFO] Installing environment for https://github.com/jorisroovers/gitlint.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
black....................................................................Passed
gitlint..................................................................Failed
hookid: gitlint

2: B4 Second line is not empty: "from unittest.mock import patch"
... many more lines ...
```
That line is from the source file I changed as part of the commit, rather than the commit message (in fact I'm never dropped into an editor to create a commit message).

What am I missing in the config?  I don't want gitlint to run over the code that's changed in the commit, but rather my commit message.

**Comment by pzelnip** [comment]
I did that and now I get:

```
$ git commit -am "add gitlint to pre-commit config"
black................................................(no files to check)Skipped
gitlint..................................................................Failed
hookid: gitlint

Error: --msg-filename option requires an argument
```

**Comment by rico-chet** [comment]
This seems like some `pre-commit` magic running wild. Here's what works for me:

```
apt install git python3-pip
pip3 install pre-commit

git clone --mirror https://github.com/jorisroovers/gitlint

mkdir gitlint-test
cd gitlint-test
git init
git config user.email "you@example.com"
git config user.name "Your Name"
git commit --allow-empty --message="Initial empty commit"
cat > .pre-commit-config.yaml <<EOF
repos:
  - repo: ../gitlint.git
    rev: master
    hooks:
    - id: gitlint
      stages:
      - commit-msg
EOF
git add .pre-commit-config.yaml
git commit --message="Add pre-commit config"
pre-commit install --install-hooks --hook-type commit-msg
touch foo
git add foo
git commit
```

**Comment by pzelnip** [comment]
I really am not interested in having a local clone of gitlint that I have to refer to in a relative path setting, as that's not feasible for my use-case (having a config for a repo shared across a team).

Closing as I'm not interested in pursuing this further.  Thanks for trying.

**Comment by asottile** [comment]
This PR will fix this: https://github.com/jorisroovers/gitlint/pull/72

Someone erroneously removed the `stages: [commit-msg]` I had put there :S
