### ISSUE TITLE
Intermittent test failures make development difficult

### ISSUE THREAD

**Issue by pbregener** [jorisroovers/gitlint#77]
Adding features to `gitlint` (or improving existing ones) is unfortunately pretty difficult due to intermittently failing integration tests. This can also be seen in simple pull requests such as #73.

I tried a few things in #76, but haven't been able to fix it so far.

My feeling is that it is related to unicode string handling, possibly also in connection with an outdated version of `sh` that returns the strings that are compared to the reference result. The [sh changelog](https://github.com/amoffat/sh/blob/master/CHANGELOG.md) shows quite a few unicode-related bugs being fixed in versions newer than the one currently used by `gitlint`. Those newer versions appear to be incompatible with `gitlint` today, so simply updating the dependency is not enough.

**Comment by jorisroovers** [comment]
Thanks for your ongoing interest and contributions to gitlint :-)

This is a problem I've been experiencing for a long time and also haven't been able to definitely figure out what's going on. I agree that it's probably related to unicode handling.

Will keep this open for ongoing tracking.
