### ISSUE TITLE
.git/hooks/commit-msg: 24: read: Illegal option -e

### ISSUE THREAD

**Issue by wturrell** [jorisroovers/gitlint#8]
I get this error on a Vagrant box using Ubuntu 14.04.3 LTS (and because it's in a while loop it was printed over and over again.)

I removed the `-e` switch from line 24 and gitlint seemed to work correctly but I haven't been able to find anything which specifies what `-e` is supposed to do?

**Comment by jorisroovers** [comment]
So the ```-e``` flag allows you to browse through your command history using your arrow keys as potential input values for the read command. I don't recall the exact reason for putting it there, but I think  it's probably kinda useless and as you indicated apparently not widely supported. We should get rid of it if it doesn't break things.

Should be an easy fix, I'll look into it once I find some time.

**Comment by jorisroovers** [comment]
Apologies for the delay @wturrell and thanks again for submitting. This will go out with the next release.

**Comment by wturrell** [comment]
No problem.
