### ISSUE TITLE
Read configuration from setup.cfg and tox.ini?

### ISSUE THREAD

**Issue by barbossa** [jorisroovers/gitlint#82]
gitlint can read configuration options from `.gitlint`. Is it possible add feature for reading options from `setup.cfg` and `tox.ini`?

For example flake8 can read configuration options from `.flake8`, `setup.cfg`, or `tox.ini` files. It is very convenient

**Comment by jorisroovers** [comment]
Yes, I like this idea. I'll mark this as a feature enhancement - no immediate ETA (probably a while).

**Comment by jorisroovers** [comment]
I have changed my mind on this and mostly agree with @webknjaz's and @sigmavirus24 assessment at this point.
  
Supporting extra formats is a lot of maintenance overhead that I'm not willing to take on right now and it indeed can cause some complexity on the user side as well.

Having said that, with the pervasiveness of `pyproject.toml` these days, I have had some second thoughts about #115 and whether longer term we should consider supporting it. I know for gitlint itself I'm considering moving to `pyproject.toml` entirely (or as much as possible). To be clear: I mean **only** supporting `pyproject.toml` in addition to `.gitlint(.ini)`. No support for `tox.ini` or `setup.cfg` as per the reasons stated.

I think the preference of having everything sit in `pyproject.toml` or keep them all in separate config files is exactly that: preference. I can see that the occasional python developer or small project maintainer might be more inclined towards the single file for everything approach to declutter the project root - it's definitely something that speaks to me. For multi-project maintainers with more standardized and automated setups, I can relate to @webknjaz's arguments. I've worn both hats and again, think it's mostly about preference and context.

**Comment by webknjaz** [comment]
@jorisroovers I think if you'll be adding TOML parsing, extending the lookup to also check for `.gitlint.toml` wouldn't be too much of a burden. But maybe it should happen at a point where Gitlint will want to support more complex configuration that INI just can't cater sanely.

**Comment by sigmavirus24** [comment]
Personally, gitlint isn't a project specific to python. To the best of my knowledge people use it who aren't using it on python projects. Switching to TOML might be nice but it's not as common as a format as would be nice if we're supporting a new format. Further supporting pyproject.toml only helps python projects, not anyone else. It then introduces a filename as an option that makes no sense to anyone outside the python community. I'm not fond of that, personally. Gitlint is written in python but it's not just for python people

**Comment by jorisroovers** [comment]
Thanks for the big-picture perspective @sigmavirus24, I think that's an excellent point about gitlint not just being for python projects - I admittedly lost sight of that for a moment. While I still think it doesn't hurt to *also* support `pyproject.toml`, I agree it could be confusing to non-python users. If I ever do get to the point of wanting to implement it, let's have another discussion about it.

Closing this particular ticket now as it was specific about `tox.ini` and `setup.cfg`.  Appreciate all the input 🙏
