### ISSUE TITLE
Is there a configuration template for validating against the conventionalcommits.org spec?

### ISSUE THREAD

**Issue by petemounce** [jorisroovers/gitlint#84]
I just came across gitlint via searching for a golang implementation of https://conventional-changelog.github.io/commitlint/#/, which validates against the https://www.conventionalcommits.org/en/v1.0.0-beta.3/ spec.

It looks like gitlint is pretty configurable; I was wondering whether anyone had created a `.gitlint` config that made it validate against the CC spec? If not - would one be welcome?

(I'd prefer to use a golang based tool, personally, since the environment is simpler to deploy and maintain for engineers - copy a binary, run it, vs maintain a node and npm setup.)

**Comment by jorisroovers** [comment]
Thanks for your interest in gitlint!

I definitely welcome more example gitlint files - this could just go under the ```examples``` directory.

> I'd prefer to use a golang based tool, personally, since the environment is simpler to deploy and maintain for engineers - copy a binary, run it, vs maintain a node and npm setup.

Not sure if this is a question, but I hope it's clear that I won't be able to help you with this. Gitlint is python-based and that won't change. I think there's room for multiple implementations in different languages: depending on your ecosytem you'll want something that aligns with it.

Thanks!

**Comment by danielgtaylor** [comment]
I've been using this to enforce conventional commits:

`.gitlint`
```ini
[general]
ignore=body-is-missing

# Load custom conventional commit rules.
extra-path=gitlint-rules.py
```

`gitlint-rules.py`
```py
import re
from typing import List

from gitlint.git import GitCommit
from gitlint.options import ListOption
from gitlint.rules import CommitMessageTitle, LineRule, RuleViolation

_rule_re = re.compile(r"[^(]+?(\([^)]+?\))?: .+")


class ConventionalCommit(LineRule):
    """This rule enforces the spec at https://www.conventionalcommits.org/."""

    # A rule MUST have a human friendly name
    name = "title-conventional-commits"

    # A rule MUST have an *unique* id, we recommend starting with UL (for
    # User-defined Line-rule), but this can really be anything.
    id = "UL1"

    # A line-rule MUST have a target (not required for CommitRules).
    target = CommitMessageTitle

    # A rule MAY have an option_spec if its behavior should be configurable.
    options_spec = [
        ListOption(
            "types",
            ["fix", "feat", "chore", "docs", "style", "refactor", "perf", "test"],
            "Comma seperated list of allowed commit types.",
        )
    ]

    def validate(self, line: str, commit: GitCommit) -> List[RuleViolation]:
        violations = []

        for commit_type in self.options["types"].value:
            if line.startswith(commit_type):
                break
        else:
            violations.append(
                RuleViolation(
                    self.id,
                    f"Title does not start with one of "
                    f"{', '.join(self.options['types'].value)}: {line}",
                )
            )

        if not _rule_re.match(line):
            violations.append(
                RuleViolation(
                    self.id,
                    f"Title does not follow ConventionalCommits.org format "
                    f"like 'type(optional-scope): description': {line}",
                )
            )

        return violations
```

Then just run `gitlint` and it should get picked up. What do you think? Would something like this be worth adding as an optional (default off) title rule? Having to put this in a separate file in each repo is kind of a pain, so getting it officially added to gitlint or supporting plugins via `pip install ...` would be better!

**Comment by jorisroovers** [comment]
I added this as an example of the newly added Contrib rules, see #88.

This will go out as part of the next gitlint release (0.12.0) - I'm not sure when that will be, anywhere between a few days and a few months :-)

**Comment by php-coder** [comment]
> ["fix", "feat", "chore", "docs", "style", "refactor", "perf", "test"],

@danielgtaylor @jorisroovers Thanks! Please, consider adding `revert` as well.

**Comment by esciara** [comment]
> This will go out as part of the next gitlint release (0.12.0) - I'm not sure when that will be, anywhere between a few days and a few months :-)

Great stuff! This is one of the things I was looking for... What kind of help would you need for it to be a few days rather than a few months?!

**Comment by jorisroovers** [comment]
@danielgtaylor while this would be straightforward to add, I also feel like this is easily configurable:
```ini
[contrib-title-conventional-commits]
types = fix,feat,chore,docs,style,refactor,perf,test,revert
```
How common is the **revert** keyword when using conventional commit? I couldn't find a reference to it on [the homepage](https://www.conventionalcommits.org/en/v1.0.0-beta.3/).

@esciara Nudges like this typically help :-) I just need to wrap up some other minor things. I'll try to get it out over next 1-2 weeks.

**Comment by php-coder** [comment]
> How common is the revert keyword when using conventional commit?

Here is the quote:

>Others: commit types other than fix: and feat: are allowed, for example @commitlint/config-conventional (based on the the Angular convention) recommends chore:, docs:, style:, refactor:, perf:, test:, and **others**.

The links to commitlint and Angular convention mention revert:
- https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional#type-enum
- https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#revert

**Comment by jorisroovers** [comment]
Added 'revert' keyword in e95fe6122fae5930534f46dfc15dcd3bb7cf8059

Gitlint 0.12.0 with support for this will be released over the next few days. Closing this issue.
