### ISSUE TITLE
v0.11.0 release?

### ISSUE THREAD

**Issue by nickbroon** [jorisroovers/gitlint#85]
Some good bug fixes since the last release. Would be great to see a v0.11.0 release that could be packaged.
https://github.com/jorisroovers/gitlint/compare/v0.10.0...master

**Comment by jorisroovers** [comment]
Thanks for you interest. It's been hard to make time to maintain gitlint for me over the past year, hence the delay... I'll try to get a release out over the next week.

**Comment by jorisroovers** [comment]
Just released v.0.11.0, in which I believe I've fixed #78 which I know you were looking for. Let me know if it works for you.

I'll keep this ticket open for a bit longer for any follow-up.

**Comment by nickbroon** [comment]
Thanks for fixing the issues and making a release.
