### ISSUE TITLE
Feature suggestion: print full commit msg to stdout if aborted

### ISSUE THREAD

**Issue by wturrell** [jorisroovers/gitlint#9]
Supposing I run `git commit` and write a longish message (e.g. a couple of paragraphs in the body) using my editor of choice. There's an error though, I've left a trailing period in the first line.

`Continue with commit anyways (this keeps the current commit message)? [y/n]`

If I answer 'n' to that, next time I commit I've lost all my original text.  If someone chooses `n`, could you print the full message they entered underneath so they can copy and paste it back into the editor?

(Unless you think the correct action is to commit anyway and then amend it.)

**Comment by jorisroovers** [comment]
More than reasonable request :-)

It's unlikely that I'll have time to work on this in the next week or so, but I'll look into it for the next release.

Thanks!

**Comment by wturrell** [comment]
Thanks :)
