### ISSUE TITLE
Display the failed message

### ISSUE THREAD

**Issue by zaufi** [jorisroovers/gitlint#90]
In case of failure **please display the whole message**, so I can copy-n-paste it next time (and not to start typing over and over again)...

**Comment by jorisroovers** [comment]
Hi! Can you provide a bit more detail? 

When using gitlint to lint an existing commit, the commit message is just present in the git log (```git log -1```). I don't think it's desirable to print out the entire message again (I've personally never used a linter that behaves like that).

When using gitlint as a git commit-msg hook, it will actually already print the entire commit message in case you abort your commit.

Not sure if I understood your request correctly though...

**Comment by zaufi** [comment]
I use my `$EDITOR` to write a commit message w/ the `pre-commit` hooks. When `gitlint` failed for any reason I see smth like this:

    Commit message check.....................................................Failed
    hookid: gitlint

    1: T7 Title does not match regex (^(\[[A-Z0-9]+-[0-9]+\]|(Build|Documentation|Feature|Fix|Improvement|Misc|Package|Refactor|Release|Style|Testing|WIP):) .*$)

After it failed, I have to write (the loooong) commit message **again**.

I'll be nice to have the whole content of the failed message on the failed output, so I can copy-n-paste it into an editor again and fix it to fulfill the format...

**Comment by jorisroovers** [comment]
So I don't think the linter (i.e gitlint) itself should print out the whole commit message again, but I agree that it's useful for the hook to do so after invocation in case of cancellation or errors. 

Gitlint's built-in commit-msg hook will in fact do this, but I don't believe pre-commit does this.

Paging @asottile, pre-commit maintainer.

**Comment by asottile** [comment]
yeah pre-commit doesn't do that, but you could `cat .git/COMMIT_EDITMSG` on failure probably (?)

or even do something like this:

```yaml
-   repo: local
    hooks:
    -   id: cat-msg
        name: here is the commit message
        entry: cat
        language: system
        verbose: true
```

related there's also this if you'd like to hack on it: https://github.com/pre-commit/pre-commit/issues/833

**Comment by pylipp** [comment]
I found out that using `git commit --edit --file .git/COMMIT_EDITMSG` allows you to edit the message that made the gitlint commit-msg hook fail.

**Comment by zaufi** [comment]
> I found out that using `git commit --edit --file .git/COMMIT_EDITMSG` allows you to edit the message that made the gitlint commit-msg hook fail.

I work w/ `worktree` extensively and there is no `.git/` subdirectory... so I transformed your command into the alias `!git commit --edit --file $(git rev-parse --git-path COMMIT_EDITMSG)`
