### ISSUE TITLE
Unable to allow empty body

### ISSUE THREAD

**Issue by paranoidi** [jorisroovers/gitlint#98]
I was not able to figure out in an hour how to allow empty body in commit messages. VERY frustrating. Please improve documentation and/or provide instructions.

**Comment by jorisroovers** [comment]
Thanks, this is valid feedback. I've pushed some [docs changes to the homepage](http://jorisroovers.github.io/gitlint/#configuration) that hopefully better convey how to configure gitlint and where to learn more.

In case you're still looking for your particular use-case:
Using `.gitlint` file:
```ini
[general]
ignore=body-is-missing
```
Using commandline:
```sh
gitlint --ignore body-is-missing
```
Hope this helps!

**Comment by paranoidi** [comment]
@jorisroovers you should really revamp the whole consistency of sample file, configuration file and command output. There is no apparent connection from messages to configuration file that I can figure out.

`3: B5 Body message is too short (16<20): "- test foo bar`

B5 is not mentioned in sample file in anywhere. Neither is the limit of 20. Which section should I put this rule under, and using what name key name? Sme samples from CLI some use code like `B1.line-length=100` but others are using text like `title-max-length.line-length=80`

This is inconsistent mess currently.

I would say ALL errors reported by the gitlint should use THE EXACT configuration key they fall under using standard dotted notation.

Like here good output would be:

`B5.min_length: Body message is too short (16<20): - test foo bar`
If it were configured in configuration like

```
[B5]
min_length=20
```

OR

`body.min_length: Body message is too short (16<20): - test foo bar`

If it were configured in configuration like

```
[body]
min_length=20
```

This is EXACT 1:1 map, no any fuzz or wondering.

Aso either all configuration keys should be in text for OR code form, currently they are randomly. If you stick with codes, they should be used for explicitly ignoring one rule (like in linters).

Ie.
```
[global]
ignore=B1,B2
```

**Comment by sigmavirus24** [comment]
@paranoidi I just follow this repository and I don't maintain it or contribute to it much. I just wanted to point out, your entire tone here is absolute shit.

@jorisroovers says in the README:

> I'm looking for contributors that are interested in taking a more active co-maintainer role as it's becoming increasingly difficult for me to find time to maintain gitlint. Please open a PR if you're interested - Thanks!

Given that they can't find time to maintain it, and given that they were polite and helpful in spite of the lackluster issue you opened, one might expect you to show some reciprocal respect. Instead your shitting all over their effort that they've put forth at no cost to you.

If you want better docs or you want a better tool, maybe step up and help maintain this, otherwise, take a different tact. You ask for improvements here, maybe you should make them, but I suppose you value your time too highly to be respectful, kind, or to even do the work.

**Comment by jorisroovers** [comment]
Howdy :-)

@sigmavirus24, I **really** appreciate your comment. I did have an initial *WTF* reaction to this comment. Like you pointed out, I'm trying my best here and am indeed doing this for free as a hobby. A little courtesy goes a long way. The web is full of blog posts about how open-source maintainers get burned out by this stuff...

In any case, to get on topic, I actually disagree.

It's not uncommon for linters to allow you to refer to the rule by their id or name. In fact, I got that idea [from pylint](https://docs.pylint.org/en/latest/faq.html#do-i-have-to-remember-all-these-numbers).

So it was a deliberate choice to allow users to be able to refer to rules by their id or by their name, for convenience purposes. 

In addition, the very first ```.gitlint``` example under the [Configuration section on the website](http://jorisroovers.github.io/gitlint/#configuration), points this out:

```ini
[general]
# Ignore certain rules (comma-separated list), you can reference them by their id or by their full name
ignore=body-is-missing,T3

# Ignore any data send to gitlint via stdin
ignore-stdin=true

# Configure title-max-length rule, set title length to 80 (72 = default)
[title-max-length]
line-length=80

# You can also reference rules by their id (B1 = body-max-line-length)
[B1]
line-length=123
```

I think its unlikely that I'll change this behavior, unless you can make a more compelling (and courteous) argument.

If we need to improve the docs or example files, which is likely, then I appreciate a PR or a more specific suggestion at this point.

No harm done. Thanks!

**Comment by paranoidi** [comment]
@sigmavirus24 Noted, toned down the text. It is not my intention to attack anyone, but I stand by my original assessment. 

I've maintained my share of open source mess, which you can see from my profile, although since migrating to github 1000+ tickets from trac days we lost ..

Especially after that I strongly believe fresh (frustrated) user experience to be extremely valuable. As a developer or a seasoned user you are blind to the pains of a new user.

**Comment by paranoidi** [comment]
@jorisroovers Let me at least leave something good comments behind so this criticism doesn't leave brown taste like @sigmavirus24 pointed out ..

Python code is looking very nice and has very well designed architecture which allows plugging rules in very nicely! It's just the configuration part that I think could have been a more approachable. 

After skimming the code through I understand the configuration challenges and choices a lot better.

**Comment by jorisroovers** [comment]
Thanks @paranoidi, that's a big compliment :-)

Really appreciate the PRs #100 and #101!

Here's to hopefully many more discussions and PRs! 🍻
