### ISSUE TITLE
Ignore revert commits

### ISSUE THREAD

**Issue by retr0h** [jorisroovers/gitlint#99]
Would love the ability to ignore revert commits.  This would be quite useful.

**Comment by jorisroovers** [comment]
Yup, been on the TODO list for a while. Will see if I can find some time for this in next few weeks.

**Comment by Alexander-Scott** [comment]
Hi @jorisroovers, we love this feature and were wondering if you could create a new release with it included, say 0.12.1. We would really appreciate it as we are running into some linting issues with reverts and urgently need this feature.

**Comment by jorisroovers** [comment]
I know... Have been wanting to push a release with additional changes for a few months, just haven't gotten around to it. Still need to finish some things up. I'll try to make time for it soonish. 

Not sure if this is an option in your environment and whether you're aware, but [pip can install directly from github](https://stackoverflow.com/questions/13685920/install-specific-git-commit-with-pip). That might be a good temporary workaround.
```sh
$ pip install git+git://github.com/jorisroovers/gitlint.git@73499c5f56fa2c788dd80572815c61164791c011
```

**Comment by jorisroovers** [comment]
Took me a long time to get 0.13.0 out the door, even though I implemented this months ago... In any case, this is released now.
